In [1]:
import numpy as np

In [2]:
def translate(tx,ty):
    
    M = np.array([[1, 0, tx], 
                  [0, 1, ty], 
                  [0, 0, 1]])
    
    print("Composite Matrix, M:")
    print(M)
    
    A_old = np.array([36, 2, 1])  # P = (36, 2)
    A = np.dot(M, A_old)
    print("New Coordinate of A, A': ({})".format(A))
    
    
    B_old = np.array([57, -21, 1])  # P = (57, -21)
    B = np.dot(M, B_old)
    print("New Coordinate of B, B': ({})".format(B))
    
    
    C_old = np.array([4, 100, 1])  # P = (4, 100)
    C = np.dot(M, C_old)
    print("New Coordinate of C, C': ({})".format(C))

In [3]:
tx = 21
ty = -16
translate(tx, ty)

Composite Matrix, M:
[[  1   0  21]
 [  0   1 -16]
 [  0   0   1]]
New Coordinate of A, A': ([ 57 -14   1])
New Coordinate of B, B': ([ 78 -37   1])
New Coordinate of C, C': ([25 84  1])


In [4]:
def rotate():
    
    theta = -36 # Since, 36 degree clockwise
    
    M = np.array([[round(np.cos(theta),2), round(-np.sin(theta),2), 0], 
                  [round(np.sin(theta),2), round(np.cos(theta),2), 0], 
                  [0, 0, 1]])
    
    print("Composite Matrix, M:")
    print(M)
    
    A_prime = np.array([57, -14, 1]) # A' = (57, -14)
    A_double = np.dot(M, A_prime)
    print("New Coordinate of A', A'': ({})".format(A_double))
    
    B_prime = np.array([78, -37, 1]) # B' = (78, -37)
    B_double = np.dot(M, B_prime)
    print("New Coordinate of B', B'': ({})".format(B_double))
    
    C_prime = np.array([25, 84, 1]) # C' = (25, 84)
    C_double = np.dot(M, C_prime)
    print("New Coordinate of C', C'': ({})".format(C_double))

In [5]:
 rotate()

Composite Matrix, M:
[[-0.13 -0.99  0.  ]
 [ 0.99 -0.13  0.  ]
 [ 0.    0.    1.  ]]
New Coordinate of A', A'': ([ 6.45 58.25  1.  ])
New Coordinate of B', B'': ([26.49 82.03  1.  ])
New Coordinate of C', C'': ([-86.41  13.83   1.  ])


In [6]:
def scale():
    x1, y1 = 14, 57
    x2, y2 = 37, 78
    x3, y3 = -84, 25
    
    sx = 1.4
    sy = 2.0
    
    A_scaled = x1 * sx, y1 * sy
    print("New Coordinate of A'', A''':", A_scaled)
    
    B_scaled = x2 * sx, y2 * sy
    print("New Coordinate of B'', B''':", B_scaled)
    
    C_scaled = x3 * sx, y3 * sy
    print("New Coordinate of C'', C''':", C_scaled)

In [7]:
scale()

New Coordinate of A'', A''': (19.599999999999998, 114.0)
New Coordinate of B'', B''': (51.8, 156.0)
New Coordinate of C'', C''': (-117.6, 50.0)


In [8]:
M1 = np.array([[0.81, 0.59, 0],
               [-0.59, 0.81, 0],
               [0, 0, 1]])
print("M1:")
print(M1)

A_r = np.array([57, -14, 1])
A_rotate = np.dot(M1, A_r)
print("A_rotate:", A_rotate)

M1:
[[ 0.81  0.59  0.  ]
 [-0.59  0.81  0.  ]
 [ 0.    0.    1.  ]]
A_rotate: [ 37.91 -44.97   1.  ]


In [9]:
B_r = np.array([78, -37, 1])
B_rotate = np.dot(M1, B_r)
print("B_rotate:", B_rotate)

B_rotate: [ 41.35 -75.99   1.  ]


In [10]:
C_r = np.array([25, 84, 1])
C_rotate = np.dot(M1, C_r)
print("C_rotate:", C_rotate)

C_rotate: [69.81 53.29  1.  ]


In [11]:
A_last = 38 * 1.4, -45 * 2.0
print("A_last:", A_last)

B_last = 41 * 1.4, -76 * 2.0
print("B_last:", B_last)

C_last = 70 * 1.4, 53 * 2.0
print("C_last:", C_last)

A_last: (53.199999999999996, -90.0)
B_last: (57.4, -152.0)
C_last: (98.0, 106.0)
